name: rawraffe
favicon: null
layout_spectrum: 0.50959
typography_spectrum: 0.74051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#241e20'
    - '#4d4d51'
    - '#a2a3a4'
    - '#c7c8c9'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
