name: rawraffe
favicon: null
layout_spectrum: 0.6061217505484819
typography_spectrum: 0.9038805870804936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.48024359392002225
  lightness: 0.3795818642247468
  saturation: 0.06957688741385937
  rhythmicContrast: 0.3335046246647835
purpose: []
